ReviewApp.ConsoleApp/ReviewApp.WebApp/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ReviewApp.Domain;
using ReviewApp.DataAccess;
using ReviewApp.DataAccess.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;

namespace ReviewApp.WebApp.Controllers
{
    
    public class RestaurantController : Controller
    {
        private readonly IReviewRepo _repo;
        
        public RestaurantController(IReviewRepo repo)
        {
            _repo = repo;
        }
        public static int restaurantid;
        //Get all list of restaurants
        public IActionResult Index()
        {
            var restaurants = _repo.GetAllRestaurants();

            return View(restaurants);
        }

        //Search for a restaurant
        public IActionResult SearchForARestaurantForm()
        {
            return View();
        }
        //Show the search results
        public IActionResult ShowSearchResults(string searchString)
        {
             if (searchString == null)
             {
                 return NotFound();
             }
             var foundRestaurant = _repo.FindARestaurant(searchString);
             
             if (foundRestaurant == null)
             {
                 return NotFound();
             }
             //add all found restaurants to List<>
             List<ReviewApp.Domain.Restaurant> restaurants = new List<ReviewApp.Domain.Restaurant>();
             restaurants.Add(foundRestaurant);

             return View("Index", restaurants);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        //Get restaurant details
        public IActionResult Details2(int? id)
        {
            var restaurant = _repo.GetAllRestaurants().First(x => x.Id == id);
            
            return View(restaurant.Name);
        }
        public IActionResult Details(int id)
        {
            List<ReviewApp.Domain.ReviewJoin> reviewjoins = _repo.GetReviewJoins();
            var restaurant = _repo.GetAllRestaurants().First(x => x.Id == id);
            RestaurantController.restaurantid = restaurant.Id;

            decimal averagerating = AverageRating(restaurant.Name);

            //get all reviews belonging to the restaurant
            for (int i = 0; i < reviewjoins.Count; i++)
            {
                if (reviewjoins[i].RestaurantId == restaurant.Id)
                {
                    var foundReview = _repo.SearchReviewByReviewId(reviewjoins[i].ReviewId);
                    return View(foundReview);
                }
            }
            return View();
        }

        //Average rating
        public decimal AverageRating(string restaurantname)
        {
            decimal sum = 0;
            int n = 1;
            var foundRestaurant = _repo.FindARestaurant(restaurantname);
            List<ReviewApp.Domain.ReviewJoin> reviewjoins = _repo.GetReviewJoins();
            for (int i = 0; i < reviewjoins.Count; i++)
            {
                if (reviewjoins[i].RestaurantId == foundRestaurant.Id)
                {
                    Domain.Review foundReview = _repo.SearchReviewByReviewId(reviewjoins[i].ReviewId);
                    sum += foundReview.Rating;
                    n += 1;
                }
            }
            decimal averageRating = Math.Round(sum/n, 2);
            return averageRating;
        }

        //Leave reviews
        public IActionResult Review(int id)
        {
            return View(_repo.GetReviews().First(x => x.Id == id));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult LeaveReviews()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LeaveReviews(ReviewApp.Domain.Review review)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            
            int customerId = UserController.userid;//CustomerId??
            int restaurantId = RestaurantController.restaurantid;//RestaurantId??
            //If customerId = 0 that means they were logged out, please log in again
            
            if (customerId == 0) return View("ErrorMessage", model: "Please logout and log in again!");
            _repo.AddReview(review);
            List<ReviewApp.Domain.Review> reviews = _repo.GetReviews();
            int id = reviews[reviews.Count - 1].Id;

            
            ReviewApp.Domain.ReviewJoin reviewjoin = new ReviewApp.Domain.ReviewJoin(restaurantId, customerId, id);
            _repo.AddAReviewJoin(reviewjoin);

            return RedirectToAction("Review", new { id });
        }
       
    }
}

ReviewApp.ConsoleApp/ReviewApp.WebApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ReviewApp.Domain;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;


namespace ReviewApp.WebApp.Controllers
{
    public class UserController : Controller
    {
        public static int userid;
        private readonly IReviewRepo _repo;
        public UserController(IReviewRepo repo)
        {
            _repo = repo;
        }

        [Authorize]
        public IActionResult Index()
        {
            TempData["Message"] = "you login successfully!";
            return View();
        }
        public IActionResult Details(int id)
        {

            return View(_repo.GetAllCustomers().First(x => x.Id == id));
        }
        [HttpGet]
        public IActionResult CreateAnAccount()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateAnAccount(ReviewApp.Domain.Customer customer)
        {
            //validation check
            //if(!ModelState.IsValid)
            //{
            //    return View();
            //}

            List<ReviewApp.Domain.Customer> customers = _repo.GetAllCustomers();
            
            int id = customers[customers.Count - 1].Id;
            try
            {
                _repo.AddAUser(customer);
            }
            catch( InvalidOperationException e)
            {
                ModelState.AddModelError("Email", e.Message);
                ModelState.AddModelError("Username", e.Message);
                return View();
            }
           
            return RedirectToAction("Details", new { id });
        }

        //Log-in
        
        [HttpGet("login")]
        public IActionResult LogIn(string returnUrl)
        {
            
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }
        [HttpPost("login")]
        public async Task<IActionResult> Validate(string username, string password, string returnUrl)
        {
            ViewData["ReturnUrl"] = returnUrl;
            
            var user = _repo.SearchUsersByUserName(username);
            userid = user.Id; //stored this value for add reference to ReviewJoin table

            if (username == user.UserName && password == user.Password)
            {
                var claims = new List<Claim>();
                claims.Add(new Claim("username", username));
                claims.Add(new Claim(ClaimTypes.NameIdentifier, username));
                
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                await HttpContext.SignInAsync(claimsPrincipal);
                if (returnUrl == null) return RedirectToAction("Index");
                return Redirect(returnUrl);
                
            }
            
            TempData["Error"] = "Login fail. Password or Username is invalid";
            return View("login");
        }

        //log out
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        //Denied page if a user is not an admin
        [HttpGet("denied")]
        public IActionResult Denied()
        {
            return View();
        }
        

    }
}

ReviewApp.ConsoleApp/ReviewApp.WebApp/Views/Shared/ErrorMessage.cshtml
@model string

<p>Error</p>
<p>@Model</p>

ReviewApp.ConsoleApp/ReviewApp.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReviewApp.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReviewApp.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="SearchForARestaurantForm">Search</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="CreateAnAccount">Register</a>
                        </li>
                        @*<li class="nav-item" style="position:absolute; right:20%">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogIn">Log In</a>
                        </li>*@

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ReviewApp.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>